### ISSUE TITLE
localhost:8080 -> localhost didn’t send any data.

### ISSUE THREAD

**Issue by ande-zake** [allaboutapps/go-starter#269]
I was running successfully from docker compose, and swagger ui (localhost:8081) could be opened from browser, but there is error when access go-service at localhost:8080

these are error captures.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/32786676/235292605-f1afb268-48af-45d6-9d35-eaa289db1b35.png">

<img width="528" alt="image" src="https://user-images.githubusercontent.com/32786676/235292618-89e769fc-ffc3-42ec-95b1-ecd0405ecf99.png">
 
could you help me ?

**Comment by sebastianmacias** [comment]
Where you able to find a solution? I'm having the same issue. 

Thanks

**Comment by JarWarren** [comment]
I ran into this error and realized I hadn't run `app server -pms` (probe, migrate, seed).
